### ISSUE TITLE
metric-tags:

### ISSUE THREAD

**Issue by gordonkirkland** [int128/send-datadog-action#476]
Hi!

Thanks for making this available for use. I'm sure there isn't an issue, more of a documentation helper for me. I've configured my-awesome-metric as follows:

```
      - name: Deploy duration seconds
        uses: int128/send-datadog-action@v1
        with:
          datadog-api-key: ${{ secrets.GHA_DD_API_KEY }}
          datadog-site: datadoghq.eu
          metric-name: deploy_duration
          metric-type: count
          metric-value: 4
          metric-tags: version:${{ inputs.version }}
                       solution:${{ inputs.solution }}

```  

and i get the following view in dd

![image](https://github.com/user-attachments/assets/d2d5cf85-f6f4-4f56-8301-dd72f33ae640)

where there is only one tag created (version) and the solution tag is appended to the version:VALUE.

Can you add an example including multiple tags please.

Many thanks

**Comment by gordonkirkland** [comment]
I've solved my issue. A syntax error corrected by chatgtp whilst I converted metric-value: from a constant 4 to a calculated field!

```
      - name: Deploy duration seconds
        uses: int128/send-datadog-action@v1
        with:
          datadog-api-key: ${{ secrets.GHA_DD_API_KEY }}
          datadog-site: datadoghq.eu
          metric-name: deploy_duration
          metric-type: count
          metric-value: ${{ steps.deployment_details.outputs.deploy_duration }}
          metric-tags: |
            version:${{ inputs.version }}
            solution:${{ inputs.solution }}
```
